import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/lib/utils/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" overflow-x-hidden minh-full">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
