import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/lib/utils/Providers";
import Navigation from "@/components/global-components/Navigation";
import CartSlide from "./s/home/components/CartSlide";
import FixedBodyOnCartOpen from "./s/home/components/FixBodyOnCartOpen";
import Main from "@/components/global-components/Main";
import LoadZustandGloabalStore from "@/components/global-components/LoadZustandGloabalStore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className=" overflow-x-hidden"
      >
        <Provider>
          <Navigation />
          <CartSlide />
          <LoadZustandGloabalStore />
          <FixedBodyOnCartOpen />
          <Main>{children}</Main>
        </Provider>
      </body>
    </html>
  );
}
