import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/lib/utils/Providers";
import LogOutButton from "@/components/UserProfile";
import { useUserData } from "@/store";
import Navigation from "@/components/global-components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="w-screen min-h-screen h-full overflow-x-hidden"
      >
        <Provider>
          <Navigation />
          {children}
        </Provider>
      </body>
    </html>
  );
}
